# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_title',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='stream',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='year',
        ),
    ]
